/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jacktams' at '14/05/16 17:37' with Gradle 2.13
 *
 * @author jacktams, @date 14/05/16 17:37
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
